### ISSUE TITLE
Processing mailbox

### ISSUE THREAD

**Issue by jeroenlanters** [David-Barrett-MS/PowerShell-EWS-Scripts#1]
hi,
I am running the script, but without result. See below. It starts and then shows "processing mailbox" within a few seconds.
What can be the issue?

I checked the mailbox and it has deleted items in recovery.

PS C:\temp> .\RecoverDeletedItems.ps1 -Mailbox "XXXXXX@nXXXXXXon.com"  -archive -RestoreToFolder "Archive" -LogFile "c:\temp\log.txt" -EwsUrl "https://outlook.office365.com/EWS/Exchange.asmx"
RecoverDeletedItems.ps1 version 1.1.4 starting

Using EWS Managed API found at: C:\Program Files (x86)\Microsoft Office\root\Office16\ADDINS\Microsoft Power Query for Excel Integrated\bin\Microsoft.Exchange.WebServices.dl
l

Processing mailbox XXXX@nXXXXXXXn.com

**Comment by AlMargoi** [comment]
> hi,
> I am running the script, but without result. See below. It starts and then shows "processing mailbox" within a few seconds.
> What can be the issue?
> 
> I checked the mailbox and it has deleted items in recovery.
> 
> PS C:\temp> .\RecoverDeletedItems.ps1 -Mailbox "[XXXXXX@nXXXXXXon.com](mailto:XXXXXX@nXXXXXXon.com)" -archive -RestoreToFolder "Archive" -LogFile "c:\temp\log.txt" -EwsUrl "https://outlook.office365.com/EWS/Exchange.asmx"
> RecoverDeletedItems.ps1 version 1.1.4 starting
> 
> Using EWS Managed API found at: C:\Program Files (x86)\Microsoft Office\root\Office16\ADDINS\Microsoft Power Query for Excel Integrated\bin\Microsoft.Exchange.WebServices.dl
> l
> 
> Processing mailbox [XXXX@nXXXXXXXn.com](mailto:XXXX@nXXXXXXXn.com)

Anything useful in the LogFile? Or maybe you can use the -TraceFile parameter as well and see if you get any hints there.

**Comment by jeroenlanters** [comment]
This is the log file.

16-9-2020 09:09:29   RecoverDeletedItems.ps1 version 1.1.4 starting
16-9-2020 09:09:35   Using EWS Managed API found at: C:\Program Files (x86)\Microsoft Office\root\Office16\ADDINS\Microsoft Power Query for Excel Integrated\bin\Microsoft.Exchange.WebServices.dll
16-9-2020 09:12:42   RecoverDeletedItems.ps1 version 1.1.4 starting
16-9-2020 09:12:48   Using EWS Managed API found at: C:\Program Files (x86)\Microsoft Office\root\Office16\ADDINS\Microsoft Power Query for Excel Integrated\bin\Microsoft.Exchange.WebServices.dll

**Comment by jeroenlanters** [comment]
and the trace file:

<Trace Tag="EwsRequestHttpHeaders" Tid="13" Time="2020-09-16 08:07:43Z">
POST /EWS/Exchange.asmx HTTP/1.1
Content-Type: text/xml; charset=utf-8
Accept: text/xml
User-Agent: ExchangeServicesClient/15.00.0913.015
Accept-Encoding: gzip,deflate


</Trace>

<Trace Tag="EwsRequest" Tid="13" Time="2020-09-16 08:07:43Z" Version="15.00.0913.015">
  <?xml version="1.0" encoding="utf-8"?>
  <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Header>
      <t:RequestServerVersion Version="Exchange2013_SP1" />
    </soap:Header>
    <soap:Body>
      <m:GetFolder>
        <m:FolderShape>
          <t:BaseShape>AllProperties</t:BaseShape>
        </m:FolderShape>
        <m:FolderIds>
          <t:DistinguishedFolderId Id="archivemsgfolderroot">
            <t:Mailbox>
              <t:EmailAddress>XXXXX.XXXXX@XXXXX.com</t:EmailAddress>
            </t:Mailbox>
          </t:DistinguishedFolderId>
        </m:FolderIds>
      </m:GetFolder>
    </soap:Body>
  </soap:Envelope>
</Trace>

<Trace Tag="EwsResponseHttpHeaders" Tid="13" Time="2020-09-16 08:07:48Z">
HTTP/1.1 401 Unauthorized
request-id: cf1ef5c2-0325-4bac-b2d7-dc424cc2f5b9
X-CalculatedBETarget: AM0PR08MB5268.eurprd08.prod.outlook.com
X-BackEndHttpStatus: 401
X-RUM-Validated: 1
X-BeSku: WCS5
X-DiagInfo: AM0PR08MB5268
X-BEServer: AM0PR08MB5268
X-Proxy-RoutingCorrectness: 1
Report-To: {"group":"NelOfficeUpload1","max_age":86400,"endpoints":[{"url":"https://exo.nel.measure.office.net/api/report?cat=mdocs"}],"include_subdomains":true}
NEL: {"report_to":"NelOfficeUpload1","max_age":86400,"include_subdomains":true,"failure_fraction":1.0,"success_fraction":0.01}
X-Proxy-BackendServerStatus: 401
X-FEServer: AM3PR04CA0128
Content-Length: 0
Date: Wed, 16 Sep 2020 08:07:47 GMT
Set-Cookie: exchangecookie=95682db20c7f47de9d8153c9bab93758; expires=Thu, 16-Sep-2021 08:07:43 GMT; path=/; secure; HttpOnly
Server: Microsoft-IIS/10.0
WWW-Authenticate: Basic Realm=""
X-Powered-By: ASP.NET


</Trace>

**Comment by AlMargoi** [comment]
I do see a "HTTP/1.1 401 Unauthorized" in the EWS Trace. I used another script written by David and encountered this problem because of one of the following 2 reasons:
1. I was processing another mailbox (not mine) and I was lacking the EWS-Impersonation role assignment
OR
2. Basic authentication was blocked

I expect consistency in David's scripts, so these are the basic things I would recommend you check. You might get it working with this. I hope it helps.

**Comment by David-Barrett-MS** [comment]
Running the script with -Verbose will usually give more info so you can see at what point it is stuck.

I'll have an update for this script posted later today anyway, as the OAuth doesn't renew correctly in this one.

**Comment by jeroenlanters** [comment]
I see the problem. we need modern auth, instead of basic auth. Do you how we can use modern auth for this script?

**Comment by David-Barrett-MS** [comment]
I've just fixed and published the updated OAuth code.

To use OAuth, just use -OAuth switch (and don't provide credentials).  You'll need to download  Microsoft.IdentityModel.Clients.ActiveDirectory.dll also (which is the ADAL dll that the script uses for OAuth)

**Comment by jeroenlanters** [comment]
PS H:XXXXX\Mailbox> .\RestoreEmail.ps1 -Mailbox "XXXXX.XXXXX@XXXXX.com" -OAuth -Office365 -TraceFile "H:XXXXX\Mailbox\Log1.txt" -Verbose -Impersonate
RestoreEmail.ps1 version 1.1.6 starting
VERBOSE: Loading Microsoft.Exchange.WebServices.dll v15.00.0913.015 found at: C:\Program Files\Microsoft Office\root\Office16\ADDINS\Microsoft Power Query for Excel
Integrated\bin\Microsoft.Exchange.WebServices.dll
Using EWS Managed API found at: C:\Program Files\Microsoft Office\root\Office16\ADDINS\Microsoft Power Query for Excel Integrated\bin\Microsoft.Exchange.WebServices.dll

Processing mailbox XXXXX.XXXXX@XXXXX.com
VERBOSE: ADAL already available, no need to load dlls.
VERBOSE: OAuth completed for adm_KhanA@D60c.Onmicrosoft.com, access token expires 09/16/2020 15:19:59 +00:00
VERBOSE: Office 365 mailbox, throttling delay set to 100ms
Tracing to: H:XXXXX\Mailbox\Log1.txt
VERBOSE: Attempting to bind to folder MsgFolderRoot (XXXXX.XXXXX@XXXXX.com)
VERBOSE: FAILED to bind to folder MsgFolderRoot (XXXXX.XXXXX@XXXXX.com)
PS H:XXXXX\Mailbox>

**Comment by David-Barrett-MS** [comment]
You can't use -Impersonate when using OAuth.  The script is registered for delegate access, so you must sign in as the mailbox being accessed.  Impersonation can work with OAuth, but you'd need to register your own application in the Azure Portal and grant impersonation rights there.  Otherwise, basic auth is needed (and the authenticating account needs ApplicationImpersonation rights granted to the mailbox being accessed).
