### ISSUE TITLE
Use mailboxGUID for source and target

### ISSUE THREAD

**Issue by wewenttothemoon** [David-Barrett-MS/PowerShell-EWS-Scripts#10]
Hello, I was wondering if it was possible to use this script to specify a source and target mailbox using the mailbox GUID? 
Scenario:
I have some users on EXO that have multiple mailbox locations (auxarchives) and this is causing us issues, so I wanted to basically merge the data from the other aux archives into the primary archive. For example, user johndoe@company.com has 3 mailbox locations 
primary - 20gb
archive - 60gb
auxarchive - 24gb

I would like to migrate/merge all the data in the auxarchive to the primary archive (all on exo) and disable the auxarchive. The whole reason for this is because i have to prepare some of my users to be migrated to our new tenant, but since they had auto expanding at one point they are unable to be cutover and this is causing us major headache. help would be appreciated!

**Comment by David-Barrett-MS** [comment]
Sorry I missed this one.  For the record, EWS has no awareness of aux archives, and sees the whole archive as one mailbox.  Given this, it isn't possible to move items from the aux archive(s) to the primary archive.  It would be possible to move all items back to the primary mailbox (assuming there is space), after which the archives could be reset.
