### ISSUE TITLE
Missing $ in Merge-MailboxFolder.ps1

### ISSUE THREAD

**Issue by NeedsCoffee** [David-Barrett-MS/PowerShell-EWS-Scripts#12]
Just found there's a missing $ on line 332:
https://github.com/David-Barrett-MS/PowerShell-EWS-Scripts/blob/master/Legacy/Merge-MailboxFolder.ps1#L332

**Comment by David-Barrett-MS** [comment]
Thanks.  Fixed in v1.2.4.
