### ISSUE TITLE
Remove-DuplicateItems two questions

### ISSUE THREAD

**Issue by rosenbaaronAR** [David-Barrett-MS/PowerShell-EWS-Scripts#19]
I want to say thank you, I have been able to use the merge-mailboxfolders.ps1 successfully, but I am running into issues running Remove-DuplicateItems using Oath.  Please see below. 

 .\remove-duplicateitems -mailbox $mailbox -archive -recursefolders -Office365 -OAuth -OAuthClientID $oathclientid -OauthTenantId $oath -VerboseLogFile -logfile c:\temp\remove_duplicates.log -EwsUrl $ewsurl -whatif
_Remove-DuplicateItems.ps1 version 1.1.1 starting
Using EWS Managed API found at: C:\repos\Powershell-EWS-Scripts\Legacy\Microsoft.Exchange.WebServices.dll
Processing mailbox email@email.com
_**Unable to load locate 
Failed to load ADAL, which is required for OAuth**__

1. The instructions say to use -OathSecretKeyID but that parameter isn't available. 
2. When I run the script, I receive this error.
_Unable to load locate
Failed to load ADAL, which is required for Oath_

**Comment by David-Barrett-MS** [comment]
I've made quite a few updates in v1.1.2 which is now published.  If you still receive an error when using that version, please post back.  ADAL is not required, and MSAL would only be required for certificate auth.
