### ISSUE TITLE
Update Search-Appointments.ps1

### ISSUE THREAD

**Issue by David-Barrett-MS** [David-Barrett-MS/PowerShell-EWS-Scripts#26]
Script needs updating to validate OAuth functionality and some other improvements.  Also needs Wiki added.

**Comment by tousifsawant** [comment]
Hello David, 

I have a questions, below is the script that i am running 

$items = .\Update-FolderItems.ps1 -Mailbox $Mailbox -FolderPath "WellKnownFolderName.MsgFolderRoot" -ProcessSubfolders -Office365 -OAuth -OAuthTenantId $tenantId -OAuthClientId $clientId -OAuthRedirectUri $redirectUrl -OAuthSecretKey $secretKey -SearchFilter subject:Invoice -ListMatches

When i execute the command it gives me results of all the emails with subject consisting Invoice in it.
I have tried multiple formats like "subject:Invoice" but still i get the all the emails with Invoice in their subject, can please advise.

**Comment by David-Barrett-MS** [comment]
That shows that the search filter is working as expected?
https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-perform-an-aqs-search-by-using-ews-in-exchange#using-a-string-value-type

**Comment by David-Barrett-MS** [comment]
Also please raise a new issue rather than adding to an unrelated work item.
