### ISSUE TITLE
Merge-MailboxFolder Permissions

### ISSUE THREAD

**Issue by bwlonsdaledxc** [David-Barrett-MS/PowerShell-EWS-Scripts#28]
Hi David, trying to get this script working with certificate authorisation and think I'm struggling with permissions that need to be on the app registration.

![image](https://github.com/David-Barrett-MS/PowerShell-EWS-Scripts/assets/134379655/f796be19-cec2-4960-ba2d-576a8cdf16bd)

I have that set at the moment. The cert itself works fine against another app registration I have (it connects to the mailbox fine), and script works fine when using the secret key method, I am just swapping -OauthSecretKey for -OAuthCertificate on the command line.

The script attempts to build the list of items to move, but seems to fail: Error when querying items: You cannot call a method on a null-valued expression.

I am using Microsoft.Identity.Client.dll v4.45.0.0 (anything later fails)

**Comment by David-Barrett-MS** [comment]
Looking into this, may take me a little time.  Latest version of MSAL will only work in PS7, it fails to load in PS5.  I think the best option is to try and remove the dependency on MSAL altogether (it is only required for cert auth, but I should be able to implement that manually).

**Comment by bwlonsdaledxc** [comment]
It's working, but I am seeing the following error:-

![image](https://github.com/David-Barrett-MS/PowerShell-EWS-Scripts/assets/134379655/96e6590e-85fb-4d0e-8586-7dccde46d585)

**Comment by David-Barrett-MS** [comment]
Please can you try installing this package see if it resolves? 

Install-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform

The failure is in the trace listener, which shouldn't be fatal (though will prevent throttling detection).

**Comment by bwlonsdaledxc** [comment]
I can't, but I know a man who can probably install that :)

I can also workaround it by changing the path on line 679 from ".\Microsoft.Exchange.WebServices.dll" to the full path where it is "G:\<path>\Microsoft.Exchange.WebServices.dll" (in my case)

Could an alternative be to change that in the script to provide the full path to where it found it?

**Comment by David-Barrett-MS** [comment]
Oh, good spot - that is likely to be the issue rather than the compiler platform missing (if it works by correcting the path, you won't need to install any other packages).  Didn't realise I'd not updated the path for the EWS API (so it will only work if the script is in the same folder as the EWS API, which is my testing config).  I'll update that.

**Comment by bwlonsdaledxc** [comment]
MIne's in same folder too, but I am calling it from my wrapper script which I guess is the issue for me

**Comment by David-Barrett-MS** [comment]
Change line 679 to this:
Add-Type -TypeDefinition $TraceListenerClass -ReferencedAssemblies $EWSManagedApiPath

**Comment by bwlonsdaledxc** [comment]
Sorted, thanks

**Comment by David-Barrett-MS** [comment]
Pushed that update into v1.2.9 (now live).  Closing this one off.
