### ISSUE TITLE
Import-CalendarCSV.ps1

### ISSUE THREAD

**Issue by michevnew** [David-Barrett-MS/PowerShell-EWS-Scripts#3]
Hey David, I've been using your scripts as samples when answering questions on the different communities for years now, so first of all thanks for those. Can you please upload the Import-CalendarCSV.ps1 one to your repo? There are still some copies circulating on the net, but I prefer to use the original :)

**Comment by David-Barrett-MS** [comment]
Published to https://github.com/David-Barrett-MS/PowerShell-EWS-Scripts/blob/master/Legacy/Import-CalendarCSV.ps1

I will update this one to use OAuth at some point, but as it's a very old script it will take a little work.  I am restoring most of my scripts here with docs as time allows, but if there are any others you need before I get round to it, let me know and I can dig them out.  I'm trying to restore each one with a doc at the same time, but it is taking time for the documentation part.
