### ISSUE TITLE
Merge-MailboxFolders Throttling Handling

### ISSUE THREAD

**Issue by DP3103** [David-Barrett-MS/PowerShell-EWS-Scripts#31]
Hi David - Thanks for the awesome script. I am running in to an issue where after the throttling stall , when the job resumes - it is skipping the remaining items in the current folder.

1040 items found; attempting to move
Throttling detected, server requested back off for 191680 milliseconds
Throttling budget should now be reset, resuming operations
No results returned - assuming all items processed

![Throttle_merge_mailboxfolders](https://github.com/David-Barrett-MS/PowerShell-EWS-Scripts/assets/100478484/6d66f48e-3526-4860-af5f-7f4218b9d4cb)

**Comment by David-Barrett-MS** [comment]
Latest version of the script changes the throttling handling when timeout errors occur during batch calls.  Note that timeout errors themselves are expected during long operations, so the errors themselves aren't an issue.  Please test latest version and raise a new issue if needed.
