### ISSUE TITLE
Error (MoveItems): Exception calling "CopyItems" with "3" argument(s): "The request failed. The operation has timed out"

### ISSUE THREAD

**Issue by Martijn-Lucas** [David-Barrett-MS/PowerShell-EWS-Scripts#32]
Hi @David-Barrett-MS,
When I copy allot E-mail from a mailbox to a different mailbox, I'll get the error message below. I this someting you can look at?
![Error 2](https://github.com/David-Barrett-MS/PowerShell-EWS-Scripts/assets/135611865/4f8dc97d-42a4-45d3-8474-35022d5854a8)
I used this parameters:
![Used Settings](https://github.com/David-Barrett-MS/PowerShell-EWS-Scripts/assets/135611865/c3c56fc8-ebeb-46d5-a303-c6371fb4fade)

Thanks in advance

**Comment by David-Barrett-MS** [comment]
Sorry I missed this earlier.  For large mailboxes, the script will eventually encounter throttling, and this is expected.  It will generally handle it fine and back off as needed.  If not, you can always stop the script and start it again (for move scenarios it will pick up where it left off) - the longer you leave it before starting it again the more the throttling budget will recharge.
