### ISSUE TITLE
[MoveItems]FAILED TO LOCATE TARGET FOLDER

### ISSUE THREAD

**Issue by gkosmas** [David-Barrett-MS/PowerShell-EWS-Scripts#34]
I have used this script many times. It has saved my life a lot. 

Recently, I have had the script moving emails and then all of a sudden get multiple errors saying "[MoveItems]FAILED TO LOCATE TARGET FOLDER: <FOLDER NAME>" for each folder.

When I stop the script and start it again, it shows up throttling delay (which I understand is normal). 

Not sure if something has changed that is causing this?

**Comment by gkosmas** [comment]
Are there any logs or output that I can collect for you that will help you?

**Comment by David-Barrett-MS** [comment]
I've just published an update to the script, but I suspect it won't affect this error.  The error only occurs if the target folder can't be found.  If you are using the -CreateTargetFolder and get this error, then that implies further that the folder creation failed (could mailbox have reached quota?).

I'm going to close this one off as it's quite old, but if you do still have issues then please reopen.
