### ISSUE TITLE
The specified object was not found in the store., Default folder Root not found.

### ISSUE THREAD

**Issue by Fimlore** [David-Barrett-MS/PowerShell-EWS-Scripts#39]
HI David,

Im trying to Merge-Mailbox folders between two mailboxes,  

`.\Merge-MailboxFolder.ps1 -SourceMailbox $SourceMailbox -TargetMailbox $TargetMailbox -ProcessSubfolders -CreateTargetFolder -Copy -LogFile ".\CopyStatus.log" -Office365 -OAuth -OAuthTenantId $tenantId -OAuthClientId $clientId -OAuthSecretKey $secret`

this command returns 
```
[ErrorReported] ERROR (ThrottledFolderBind): Exception calling "Bind" with "3" argument(s): "The specified object was not found in the store., Default folder Root not found."
Failed to open target message store (NewMailbox@***.nl)
```

the only way I can get the script to connect, is using "-PathsRelativeToMailboxRoot" - but then it says its copying, yet nothing actually happens :) 

also, is it possible to merge the two boxes together, but move the items in a subfolder on the new box, while keeping hierarchy ?

**Comment by David-Barrett-MS** [comment]
The source mailbox will need FullAccess rights to the target mailbox to be able to copy.

You can specify the target folder using the -TargetFolderList parameter.  If you set the target folder to a subfolder, then all the items will be copied there (and folder structure maintained).
