### ISSUE TITLE
Wrong Item Property in Filter

### ISSUE THREAD

**Issue by MEM-85** [David-Barrett-MS/PowerShell-EWS-Scripts#42]
Line 1193: .CreationTime should be .DateTimeCreated
Line 1199: .CreationTime should be .DateTimeCreated

https://github.com/David-Barrett-MS/PowerShell-EWS-Scripts/blob/991516f562600b938cca4f3ef73517c8eed11482/Legacy/Search-Appointments.ps1#L1193C30-L1193C30

**Comment by David-Barrett-MS** [comment]
Can't blame that one on copy/paste, but also fixed in v1.2.2.  Thanks.
