### ISSUE TITLE
Error when I use application login

### ISSUE THREAD

**Issue by NigelBootheNviron** [David-Barrett-MS/PowerShell-EWS-Scripts#45]
Hi I get this error when I copy the redirect url its set to local

04/12/2023 14:25:14 [ErrorReported] ERROR (ThrottledFolderBind): Exception calling "Bind" with "3" argument(s): "The request failed. The remote server returned an error: (401) Unauthorized."
Failed to open source message store (test.user@nboothey.co.uk)

**Comment by jasonwilkening** [comment]
Did you find a solution to this?  I am having the same issue.

**Comment by NigelBootheNviron** [comment]
No sorry

Sent from Outlook for iOS<https://aka.ms/o0ukef>



[cid:NvironLTDcompactlogo100pxwide_be2f2125-3670-4182-b3ee-ed292ccd7adb.png]<https://www.nviron.co.uk/> Nigel Boothe
Technical Consultant    [cid:SocialLink_Linkedin_32x32_dc2ac5e3-37b1-474f-9549-b3ff3f3f1f35.png] <https://www.linkedin.com/company/nviron-ltd>  [cid:SocialLink_Twitter_32x32_942fed1e-6f53-41b5-a9ce-512ee6c4b9a0.png] <https://www.twitter.com/nvironltd>  [cid:instagram_logo_2016.svg(002)_8da0bba3-5312-49df-9781-c5699bf780f6.png] <https://www.instagram.com/nvironltd>


E:
T:
M:
W:
***@***.***
01928 804024
07711423718
www.nviron.co.uk<http://www.nviron.co.uk>



________________________________

**Comment by jasonwilkening** [comment]
I got it to work finally.  I just had to add the -OAuthSecretKey $secretKey to the command and then it didn't give me a redirecturl and it worked.

**Comment by David-Barrett-MS** [comment]
App permissions work, the guide is here: https://github.com/David-Barrett-MS/PowerShell-EWS-Scripts/wiki/Exchange-Online-OAuth-Configuration.

If there's an auth error, use the OAuth debug options with -Verbose and you'll usually see a useful error.
