### ISSUE TITLE
Can't Move Calendar/Tasks Items from Primary Mailbox to Archive

### ISSUE THREAD

**Issue by bwlonsdaledxc** [David-Barrett-MS/PowerShell-EWS-Scripts#50]
Same issue as happened earlier in the year - will raise a MS Ticket for it also. ErrorMoveCopy when moving items from Calendar/Tasks folder into Archive.

I've realised while working on this issue that this is causing multiple copies of Calendar/Task items to be created in the Archive folder because it can't remove the original. Every time we run the script it just creates a new copy of the item in the archive.

**Comment by David-Barrett-MS** [comment]
This was an issue on Exchange Online side and is now resolved.
