### ISSUE TITLE
How to Merge-MailboxFolder - move everything from Archive to Archive Folder in Inbox. 

### ISSUE THREAD

**Issue by KirkJohnson76** [David-Barrett-MS/PowerShell-EWS-Scripts#6]
I'm trying to collapse our archives back into an Archive folder in users inboxes.  I can't figure out how to move the entirety of the Archive to an archive folder in the inbox while still maintaining the folder structure under the new archive folder under the inbox?

I've tried -MergeFolderList @{"Archive",@("*")}
I've tried -MergeFolderList @{"Archive",@()}
I've tried -MergeFolderList @{"Archive",@("WellKnownFolder")}

**Comment by KirkJohnson76** [comment]
Fixed it with building out my @merge variable with this:
$Merge = @()
[System.Collections.ArrayList]$RootFolder = @()
$Folders = Get-MailboxFolderStatistics $User -Archive | Where {$_.ItemsInFolder -gt 0} | select FolderPath

ForEach ($Folder in $Folders)
    {$RootFolder.Add($Folder.FolderPath.Split("/")[1])}

$RootFolder = $RootFolder | Select -Unique
ForEach ($Root in $RootFolder)
    {
        # Ignore the system folders because the script isn't capable of copying them to the correct place and the data isn't needed in most cases
        If (($Root -ne "Top of Information Store") -and ($Root -ne "Recoverable Items") -and ($Root -ne "Calendar Logging") -and ($Root -ne "Deletions") -and ($Root -ne "Purges") -and ($Root -ne "Versions") -and ($Root -ne "Conversation Action Settings") -and ($Root -ne "Quick Step Settings") -and ($Root -ne "Calendar"))
        {
            $objMerge = New-Object System.Object
            $objMerge | Add-Member -Type NoteProperty -Name Name -Value "Archive\$Root"
            $objMerge | Add-Member -Type NoteProperty -Name Value -Value $Root
            $Merge += $objMerge
        }
    }

**Comment by luckman212** [comment]
@KirkJohnson76 I'm trying to do the exact same thing. Would you mind posting your `.\Merge-MailboxFolder.ps1 ...` command that you used after building your `$Merge` variable?

Is it just
```powershell
-SourceMailbox user@domain.com -SourceArchive -MergeFolderList $Merge -ProcessSubfolders -CreateTargetFolder -Copy -Office365 -OAuth
```
